import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import banner from 'rollup-plugin-banner';

const MODULE_NAME = 'MMM-ViewNotifications';

const BANNER_TEXT = [
  `MagicMirror² Module: ${MODULE_NAME}`,
  'Version: <%= pkg.version %>',
  '',
  '<%= pkg.description %>',
  '',
  'By: <%= pkg.author %>',
  'License: <%= pkg.license %>',
  '',
  'This is an autogenerated file. DO NOT EDIT!',
].join('\n');

export default [
  {
    input: `./src/${MODULE_NAME}.tsx`,
    plugins: [typescript({ module: 'ESNext' }), resolve(), commonjs(), banner(BANNER_TEXT)],
    output: {
      file: `./${MODULE_NAME}.js`,
      format: 'iife',
      globals: {
        logger: 'Log',
        moment: 'moment',
      },
    },
    external: ['logger', 'moment'],
  },
];
