import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import typescript from '@rollup/plugin-typescript';
import banner from 'rollup-plugin-banner';

const BANNER_TEXT = [
  'MMM-ViewNotifications',
  '<%= pkg.description %>',
  '',
  'Version <%= pkg.version %>',
  'By <%= pkg.author %>',
  '',
  'License <%= pkg.license %>',
  '',
  'This is an autogenerated file. DO NOT EDIT!',
].join('\n');

export default [
  {
    input: './src/MMM-ViewNotifications.ts',
    plugins: [typescript(), resolve(), commonjs(), banner(BANNER_TEXT)],
    output: {
      file: './MMM-ViewNotifications.js',
      format: 'iife',
      globals: {
        logger: 'Log',
        moment: 'moment',
      },
    },
    external: ['logger', 'moment'],
  },
];
